// Importing type only to define metadata for the layout (helps with SEO and Next.js head rendering)
import type { Metadata } from "next";

// Importing Inter font from Google Fonts using Next.js built-in optimization
import { Inter } from "next/font/google";

// Importing ToastContainer for toast notifications from react-toastify
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Importing the default CSS for toast notifications

// Global styles for the entire app
import "./globals.css";

// App-wide providers (e.g., Redux, Theme, Auth, etc.) defined in a custom Provider component
import Providers from "./Provider";

// Load Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Exporting metadata for this layout (used by Next.js for SEO and <head> rendering)
export const metadata: Metadata = {
  title: "iris", // Title shown in the browser tab
  description: "Generated by create next app", // Description for search engines
};

// Root layout component - wraps all pages and components in the app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Readonly prop to ensure children cannot be reassigned
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Applies Inter font styles to the entire body */}
        <Providers> {/* Wraps the app in any global context providers */}
          <ToastContainer autoClose={500} /> {/* Enables toast notifications across the app */}
          {children} {/* Renders the content of the current page */}
        </Providers>
      </body>
    </html>
  );
}
